version: '3.7'

services:
  keycloak:
    build:
      context: ./security/keycloak-resource-server # Adjust the context to the drivers directory
      dockerfile: ./Dockerfile  # Adjust the Dockerfile path
    container_name: keycloak
    environment:
      #Admin Credentials
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KC_DB_URL: 'jdbc:postgresql://host.docker.internal:${KEYCLOAK_POSTGRES_PORT}/${KEYCLOAK_DATABASE_NAME}'
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      KC_HOSTNAME: ${LOCAL_IP}
      PROXY_ADDRESS_FORWARDING: "true"
      #KC_PROXY: edge
      KC_SPI_THEME_DEFAULT: 'my-theme'
      QUARKUS_HTTP_LIMITS_MAX_INITIAL_LINE_LENGTH: 8192
    #network_mode: host
    command:
      #- "-v start --optimized"
      - "-v start --optimized --http-enabled=true --http-port=${KEYCLOAK_PORT} --https-port=0 "
      
    ports:
      - 8443:8443
      - ${KEYCLOAK_PORT}:${KEYCLOAK_PORT}
    networks:
      - vetsc_network

    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data

volumes:
  keycloak-data:

networks:
  vetsc_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24